import java.util.Formatter;
import java.util.UUID;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


/**
 * Hashing provides hash generation and validation functionality to other classes.
 * @version 1.0
 */
public class Hashing {

  /**
   * Generates a random hash using Java's UUID class.
   * @return A random hash to be used for identification(UUID).
   */
  public static String generateRandomHash() {
    return UUID.randomUUID().toString().replace("-", "");
  }

  /**
   * Generate a hash for a given string.
   * @param body String for which a hash will be generated.
   * @return A String representation of a hexadecimal hash value for the supplied string.
   */
  public static String generateHash(String body) {
    MessageDigest md;

    try {
      md = MessageDigest.getInstance("SHA-1");
    } catch (NoSuchAlgorithmException e) {
      return null;
    } 

    md.reset();
    md.update(body.getBytes(StandardCharsets.UTF_8));

    byte[] raw = md.digest();

    // convert to hex string
    Formatter formatter = new Formatter();
    
    for (byte b : raw) {
      formatter.format("%02x", b);
    }
    
    String hash = formatter.toString();

    formatter.close();

    return hash;
  }

  /**
   * Compares a given hash to a hash generated by the generateHash() function.
   * @param hash Hash to compare to.
   * @param body String to be hashed for comparison.
   * @return True if the hash matches the computed hash, otherwise false.
   */ 
  public static boolean checkHash(String hash, String body) {
    return hash.equals(generateHash(body));
  }
}
